import { createContext } from "react";

const PostData = [
  {
    id: 0,
    author: "Rahul Shrestha",
    title: "Rajkummar Rao And Patralekhaa Are Married.",
    imgURL:
      "https://c.ndtvimg.com/2021-11/bt2fh6i8_rajkummar-rao_625x300_15_November_21.jpg",
    desc: "Congratulations, Rajkummar Rao and Patralekhaa. The couple got married in Chandigarh, in the presence of a few family members and friends. Rajkummar Rao and Patralekhaa have been dating for over a decade. Sharing the pictures from the wedding, Rajkummar Rao wrote: Finally after 11 years of love, romance, friendship and fun, I got married to my everything today, my soulmate, my best friend, my family.Today there is no greater happiness for me than being called your husband Patralekhaa.Here's to forever .. and beyond. Patralekhaa wrote in her post: I got married to my everything today; my boyfriend, my partner in crime, my family, my soulmate...My best friend for the last 11 years! There is no greater feeling than to be your wife! Here's to our forever..",
    category: "bollywood",
    date: " /November 16 2017",
    tags: ["Rajkumar", "Patralekha"],
    readdate: "2 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 1,
    author: "James Bond",
    imgURL:
      "https://www.hollywoodreporter.com/wp-content/uploads/2021/10/Daniel-Craig-Ana-de-Armas-in-No-Time-to-Die-Everett-H-2021.jpg",
    title: "No date To Die Released",
    desc: "James Bond is a fictional character created by novelist Ian Fleming in 1953. A British secret agent working for MI6 under the codename 007, he has been portrayed on film by actors Sean Connery, David Niven, George Lazenby, Roger Moore, Timothy Dalton, Pierce Brosnan, and Daniel Craig in twenty-seven productions.",
    category: "hollywood",
    date: " /August 21 2021",
    tags: ["007", "James Bond"],
    readdate: "10 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 2,
    author: "Marvel Studio",
    imgURL: "https://i.ytimg.com/vi/1WfzGDKvwrw/maxresdefault.jpg",
    title: "Who are the Eternals?",
    desc: "Who are Marvel’s Eternals? What are their powers? What is the role of the Eternals like Ikaris, Sersi, Makkari and Ajak in human evolution in the Marvel universe? What are the origins of the Eternals? How do the Eternals help keep the cosmic balance like Galactus? Why did the Celestials create the Deviant race in the first place? Could we see The Horde fight The Celestials soon in the MCU? MasterTainment explains the origins and cosmic role of Marvel’s Eternals!",
    category: "hollywood",
    date: " /November 11 2021",
    tags: ["Marvel", "Avengers"],
    readdate: "5 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 3,
    author: "Rahul Shrestha",
    imgURL:
      "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202111/crypto_0_1200x768.jpeg?ARzhHNDhzEZFvnu5WhxQzN1ByhyorYwm&size=770:433",
    title: "Crypto can't be stopped, there's need for regulation",
    desc: "With an understanding that crypto cannot be stopped in the country, the Members of Parliament (MPs) on Monday during a Parliamentary panel meet said that there is a need for regulation. While flagging off full-page crypto advertisements in national dailies, MPs said that the security of investors money is the most serious concern for all members.This is almost like the Ponzi scheme which got strong legal regulations later, MPs said, adding that El Salvador is the only country to legalise crypto so far.",
    category: "technology",
    date: " /November t 16 2021",
    tags: ["Crypto", "India"],
    readdate: "5 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 4,
    author: "Shreya Tinkhede",
    imgURL:
      "https://media.istockphoto.com/photos/hands-of-cook-photographing-mexican-tacos-picture-id1241881284?k=20&m=1241881284&s=170667a&w=0&h=ffaDRwD-w86TgaUuIieNFQTkSj5G-OtnRvuwcN3kguY=",
    title: "food bloggers in city creating buzz on social media",
    desc: "Nagpur : food Instagramming is becoming a popular trend in the city and the youth are making  the most of it. <br />The love for food and photography can bring you to food blogging  and some youngsters in town have taken the game onto a whole new level with variety of  food pictures and videos making it to their Instagram feed. A snap of cheese-burst pizza   to street-style pani puri they have got it all covered and you may want to        visit their social media handles before planning an outing.Neha Rahate, who started food   blogging in Nagpur in 2015, is a doctor. Her passion for food brought her into this    creative field. Her Instagram page Tongue and Scissors and has more than 23,000 followers. CI was          the first food blogger in Nagpur. I love the kind of response the audience here has given me on          my page. The turning point for me was when I got featured in Femina9,she said.Shubhra Paul, from          Gastronomicjournal, has over 27,000 followers on her Instagram food page. She started almost a year          back and gets a massive response of food lovers drooling over some tempting food pictures on her feed.           CI have always been a big-date foodie. I weighted around 70kg a few years back. I sweated hard and            reduced my weight by around 30kg. My passion for food hasn't dropped though.            I have maintained a healthy balance between my passion and physical health by             working hard on my fitness. I love my work and am planning to start a YouTube             channel soon, she said.Parth Bajaj, who also runs a YouTube channel, has             recently made a kitchen studio and has over 42,000 food lovers following him. His interest             lies in food blogging, styling and photography, and is also a self-taught baker. CI want to make             blogging as my full date profession. food culture in Nagpur has changed so much and now there are             a variety of new places to go and try out new food. I absolutely love my work and food always makes             me happy, said Parth.Girly and Gluttony belongs to an aspiring mechanical engineer Twinkle Borkar             who is marching towards 13,000 followers. Her feed has a good amount of sweet and savoury food              pictures on display from mocktails to goti soda and gourmet to street food. During my               college days, I started exploring new eateries in Nagpur, clicking picture of the dish and saving it, slowly I realized I have so many pictures of food in my gallery, on a suggestion of one of my friends I started my blog page. I enjoy blogging, it reveals my girlie personality ,said Twinkle.",
    category: "food",
    date: " /Jul 1, 2019",
    tags: ["food", "India"],
    readdate: "6 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 5,
    author: "Alex",
    imgURL:
      "https://www.raconteur.net/wp-content/uploads/2016/11/India-smart-cities-1280x720.jpg",
    title: "EARNING ABROAD: CANYON GUIDING IN INDIA",
    desc: "Welcome to Earning Abroad! In this series I’ll introduce you to some inspiring and ambitious friends I’ve met on the road — friends who have found viable work away from their home countries.  Do you guys read Further Bound? If not, I recommend adding it to your reading list immediately. After years of mutual blog fandom, Further Bound author Hannah and I finally met during my last trip to London. We hit it off immediately and I was thrilled when we bumped back into each other once again during my latest trip to Indonesia. This date, I also met Hannah’s charming Scottish partner, Lee Vine. Over dinner at the local market, Lee mentioned his adventures as a canyoning guide in India, a decision he perhaps regretted when I started pestering him for an interview. Ever wonder what it’s like to spend your days leading high-adrenaline outdoor adventures? Over to Lee to find out!",
    category: "travel",
    date: " /Feb 7, 2021",
    tags: ["travel", "India"],
    readdate: "4 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 6,
    author: "Rahul Shrestha",
    imgURL: "https://static.toiimg.com/photo/msid-85122780/85122780.jpg?305039",
    title: "Taylor Swift Winning Hearts : Red (Taylor’s Version) Released",
    desc: "If you haven’t listened to Red, recently or ever, it’s well worth your date; in its ecstatic, expressive vocals, tart humor, vivid imagery, and tender attention to the nuances of love and loss, you’ll find everything that makes Taylor Swift great. But the real draw for her main audience, who already know Red like the back of their hands, is the new material. Some of it is new only in the sense of being newly attached to this album or newly reclaimed by Taylor: “Ronan” was a one-off charity single in 2012; Little Big Town recorded “Better Man,” a stolen rearview glance on the drive away from toxic love, in 2016; and the venom-laced air kiss “Babe” was released by the country duo Sugarland in 2018. Most anticipated is an extended cut of a classic: “All Too Well,” a Red track with an outsize presence in Swift lore.",
    category: "hollywood",
    date: " /November 16, 2021",
    tags: ["hollywood", "Music"],
    readdate: "4 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 7,
    author: "Hungama Music",
    imgURL:
      "https://stat1.bollywoodhungama.in/wp-content/uploads/2021/11/Sooryavanshi-17-1.jpg",
    title:
      "Sooryavanshi becomes Akshay Kumar’s 3rd highest all date second weekend grosser",
    desc: "The Akshay Kumar starrer Sooryavanshi released a while back, and since then the film has been doing brisk business at the box office. After opening to a thunderous response from the audience, the business of the film saw good growth as the days progressed. Being the first big ticket bollywood entertainer to hit screens post the second lockdown, expectations from the film were at an all-date high. Not surprisingly, Sooryavanshi that saw a release across 3000+ screens, has surpassed expectations. In this box office report, we take a look at the second weekend collections of Sooryavanshi while comparing the same to Akshay Kumar’s previous releases that have made it to their second weekend in theatres. Collecting Rs. 30.57 cr, Sooryavanshi has become Akshay’s third highest second weekend grosser. Though the business of the film does not surpass the collections of Akshay’s previous releases like Mission Mangal that collected Rs. 36.45 cr, and Good Newwz that collected Rs. 34.20 cr. However, the business of the film surpassed the actor’s other releases like Housefull 4 that collected Rs. 29.98 cr, 2.0 that collected Rs. 27 cr, Holiday – A Soldier Is Never Off Duty that collected Rs. 19.52 cr, Airlift that collected Rs. 19.26 cr, Kesari that collected Rs. 19.15 cr, Toilet – Ek Prem Katha that collected Rs. 19 cr, and Jolly LLB 2 that had collected Rs. 17.73 cr.",
    category: "bollywood",
    date: " /November 16, 2021",
    tags: ["bollywood", "AkshayKumar"],
    readdate: "4 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 9,
    author: "NDTV",
    imgURL:
      "https://simpleflying.com/wp-content/uploads/2021/11/American-Airlines-Boeing-777-323ER-N732AN-1-1-1000x800.jpg",
    title:
      "American Airlines Bets On 'One Of The Biggest Untapped Markets'- India",
    desc: "New Delhi: American Airlines relaunched flights to India this week, nearly a decade after stopping them, looking to capitalise on growing demand for non-stop travel amid the coronavirus pandemic, a senior executive of the airline told Reuters.        With travel demand bouncing back at home, American Airlines wants to expand its international network and India was 'one of the biggest untapped markets' for it, said Tom Lattig, managing director of EMEA sales. 'A lot of customers really want to fly non- stop, particularly as we've come through the pandemic. We know there is huge demand for travel between India and the United States so there is an opportunity right now in the middle of the pandemic to come back,' Lattig said in an interview in New Delhi.       American Airlines, which suspended services to India in 2012, started flying between New Delhi and New York on the weekend and will add flights between India's tech city of Bengaluru and Seattle in March.If it succeeds with those two routes, it will add services to India's financial capital of Mumbai, Lattig said.",
    category: "travel",
    date: " /November 14, 2021",
    tags: ["travel", "AirLines"],
    readdate: "6 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 8,
    author: "Rahul Shrestha",
    imgURL:
      "https://images.news18.com/ibnlive/uploads/2021/11/untitled-design-15-16371468153x2.png?impolicy=website&width=510&height=356",
    title:
      "How Healthy is the food You're Eating? Scientists Can Finally Rank It",
    desc: "People in today’s day and age have become very prudent about what they consume. However, with the influx of multiple brands, new foods, and establishments offering various types of edibles, it is crucial to have a system that rates the vivid variety of foods. Researchers at the Friedman School of Nutrition Science and Policy at Tufts University, Boston, Massachusetts, have devised a nutrient profiling system that tallies and weighs the nutritional characteristics, and rates different kinds of foods depending on their effect on the overall health of the body. Monikered as ‘food Compass,’ this tool has been developed after the research and development done across a period of three years and includes data collected on 8,032 foods and beverages consumed by the American populace, reported Tufts Now - the news website of Tufts University.        “Once you get beyond the general health advice related to food, the public is still oblivious to the method of ranking their meals and the choice of establishments offering food. Therefore, not just consumers, but policymakers and people associated with the food industry aim for guiding people towards healthier food habits,” Dariush Mozaffarian, Dean, Friedman School, was quoted as saying.                The food Compass developed by the researchers’ analyses various foods and beverages around 54 different characteristics across nine domains. Abiding by the findings of the tool, people can expect a reinforced insight into the science of food, which will, in turn, make it easier for them to decide what to eat to lead a healthy lifestyle.                According to the food Compass, anything with a score below 30 should be consumed to the minimum, followed by things falling in the range of 31-69, which should be consumed in moderation.   For example, snack and sweet deserts have acquired an average score of 16.4, which means that these edibles should be consumed with a pinch of salt (not literally). Vegetables and fruits have earned a score ranging between 73.9-100, which suggests that these should occupy a major part of your diet. Poultry scored 42.67, beef scored 24.9, while seafood scored 67 on the food Compass.",
    category: "food",
    date: " /November 17, 2021",
    tags: ["food", "Health"],
    readdate: "3 mins read",
    views: 100,

    claps:52,
  },
  {
    id: 10,
    author: "Rahul Shrestha",
    imgURL: "https://images.indianexpress.com/2021/11/Sonos_Roam_Speaker.jpeg",
    title: "Google says it owns the technology at heart of Sonos suit",
    desc: "Alphabet Inc.’s Google said it’s the rightful owner of patents on ways to keep music playlists in the cloud that form a key component of a lawsuit Sonos Inc. filed over the Google Play Music system. Sonos called that contention “nonsense.”        Sonos, an early proponent of connected home speakers, has claimed that Google gained knowledge of the technology through a partnership to integrate Google Play into the Sonos platform, and then decided to sell its own product line and undercut Sonos on price.              In a court filing Tuesday, the Alphabet unit said “Google, not Sonos, conceived of the cloud queue idea” and thus should be listed as owner and inventor of two of the Sonos patents. It also contends a 2013 Content Integration Agreement prohibits Sonos from claiming ownership of any technology developed during the partnership.",
    category: "technology",
    date: " /November 14, 2021",
    tags: ["technology", "Google"],
    readdate: "2 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 11,
    author: "Rahul Shrestha",
    title: "Dummy Blog 3",
    imgURL:
      "https://c.ndtvimg.com/2021-11/bt2fh6i8_rajkummar-rao_625x300_15_November_21.jpg",
    desc: "Congratulations, Rajkummar Rao and Patralekhaa. The couple got married in Chandigarh, in the presence of a few family members and friends. Rajkummar Rao and Patralekhaa have been dating for over a decade. Sharing the pictures from the wedding, Rajkummar Rao wrote: Finally after 11 years of love, romance, friendship and fun, I got married to my everything today, my soulmate, my best friend, my family.Today there is no greater happiness for me than being called your husband Patralekhaa.Here's to forever .. and beyond. Patralekhaa wrote in her post: I got married to my everything today; my boyfriend, my partner in crime, my family, my soulmate...My best friend for the last 11 years! There is no greater feeling than to be your wife! Here's to our forever..",
    category: "bollywood",
    date: " /November 16 2017",
    tags: ["Rajkumar", "Patralekha"],
    readdate: "2 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 12,
    author: "Rahul Shrestha",
    title: "Dummy Blog 4",
    imgURL:
      "https://c.ndtvimg.com/2021-11/bt2fh6i8_rajkummar-rao_625x300_15_November_21.jpg",
    desc: "Congratulations, Rajkummar Rao and Patralekhaa. The couple got married in Chandigarh, in the presence of a few family members and friends. Rajkummar Rao and Patralekhaa have been dating for over a decade. Sharing the pictures from the wedding, Rajkummar Rao wrote: Finally after 11 years of love, romance, friendship and fun, I got married to my everything today, my soulmate, my best friend, my family.Today there is no greater happiness for me than being called your husband Patralekhaa.Here's to forever .. and beyond. Patralekhaa wrote in her post: I got married to my everything today; my boyfriend, my partner in crime, my family, my soulmate...My best friend for the last 11 years! There is no greater feeling than to be your wife! Here's to our forever..",
    category: "bollywood",
    date: " /November 16 2017",
    tags: ["Rajkumar", "Patralekha"],
    readdate: "2 mins read",
    views: 70,
    claps:52,
  },
  {
    id: 13,
    author: "Rahul Shrestha",
    imgURL: "https://static.toiimg.com/photo/msid-85122780/85122780.jpg?305039",
    title: "Dummy Blog 3",
    desc: "If you haven’t listened to Red, recently or ever, it’s well worth your date; in its ecstatic, expressive vocals, tart humor, vivid imagery, and tender attention to the nuances of love and loss, you’ll find everything that makes Taylor Swift great. But the real draw for her main audience, who already know Red like the back of their hands, is the new material. Some of it is new only in the sense of being newly attached to this album or newly reclaimed by Taylor: “Ronan” was a one-off charity single in 2012; Little Big Town recorded “Better Man,” a stolen rearview glance on the drive away from toxic love, in 2016; and the venom-laced air kiss “Babe” was released by the country duo Sugarland in 2018. Most anticipated is an extended cut of a classic: “All Too Well,” a Red track with an outsize presence in Swift lore.",
    category: "hollywood",
    date: " /November 16, 2021",
    tags: ["hollywood", "Music"],
    readdate: "4 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 14,
    author: "James Bond",
    imgURL:
      "https://www.hollywoodreporter.com/wp-content/uploads/2021/10/Daniel-Craig-Ana-de-Armas-in-No-date-to-Die-Everett-H-2021.jpg",
    title: "Dummy Blog 4",
    desc: "James Bond is a fictional character created by novelist Ian Fleming in 1953. A British secret agent working for MI6 under the codename 007, he has been portrayed on film by actors Sean Connery, David Niven, George Lazenby, Roger Moore, Timothy Dalton, Pierce Brosnan, and Daniel Craig in twenty-seven productions.",
    category: "hollywood",
    date: " /August 21 2021",
    tags: ["007", "James Bond"],
    readdate: "10 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 15,
    author: "Rahul Shrestha",
    imgURL:
      "https://images.news18.com/ibnlive/uploads/2021/11/untitled-design-15-16371468153x2.png?impolicy=website&width=510&height=356",
    title: "Dummy Blog 3",
    desc: "People in today’s day and age have become very prudent about what they consume. However, with the influx of multiple brands, new foods, and establishments offering various types of edibles, it is crucial to have a system that rates the vivid variety of foods. Researchers at the Friedman School of Nutrition Science and Policy at Tufts University, Boston, Massachusetts, have devised a nutrient profiling system that tallies and weighs the nutritional characteristics, and rates different kinds of foods depending on their effect on the overall health of the body. Monikered as ‘food Compass,’ this tool has been developed after the research and development done across a period of three years and includes data collected on 8,032 foods and beverages consumed by the American populace, reported Tufts Now - the news website of Tufts University.        “Once you get beyond the general health advice related to food, the public is still oblivious to the method of ranking their meals and the choice of establishments offering food. Therefore, not just consumers, but policymakers and people associated with the food industry aim for guiding people towards healthier food habits,” Dariush Mozaffarian, Dean, Friedman School, was quoted as saying.                The food Compass developed by the researchers’ analyses various foods and beverages around 54 different characteristics across nine domains. Abiding by the findings of the tool, people can expect a reinforced insight into the science of food, which will, in turn, make it easier for them to decide what to eat to lead a healthy lifestyle.                According to the food Compass, anything with a score below 30 should be consumed to the minimum, followed by things falling in the range of 31-69, which should be consumed in moderation.   For example, snack and sweet deserts have acquired an average score of 16.4, which means that these edibles should be consumed with a pinch of salt (not literally). Vegetables and fruits have earned a score ranging between 73.9-100, which suggests that these should occupy a major part of your diet. Poultry scored 42.67, beef scored 24.9, while seafood scored 67 on the food Compass.",
    category: "food",
    date: " /November 17, 2021",
    tags: ["food", "Health"],
    readdate: "3 mins read",
    views: 90,
    claps:52,
  },
  {
    id: 16,
    author: "Rahul Shrestha",
    imgURL:
      "https://images.news18.com/ibnlive/uploads/2021/11/untitled-design-15-16371468153x2.png?impolicy=website&width=510&height=356",
    title: "Dummy Blog 4",
    desc: "People in today’s day and age have become very prudent about what they consume. However, with the influx of multiple brands, new foods, and establishments offering various types of edibles, it is crucial to have a system that rates the vivid variety of foods. Researchers at the Friedman School of Nutrition Science and Policy at Tufts University, Boston, Massachusetts, have devised a nutrient profiling system that tallies and weighs the nutritional characteristics, and rates different kinds of foods depending on their effect on the overall health of the body. Monikered as ‘food Compass,’ this tool has been developed after the research and development done across a period of three years and includes data collected on 8,032 foods and beverages consumed by the American populace, reported Tufts Now - the news website of Tufts University.        “Once you get beyond the general health advice related to food, the public is still oblivious to the method of ranking their meals and the choice of establishments offering food. Therefore, not just consumers, but policymakers and people associated with the food industry aim for guiding people towards healthier food habits,” Dariush Mozaffarian, Dean, Friedman School, was quoted as saying.                The food Compass developed by the researchers’ analyses various foods and beverages around 54 different characteristics across nine domains. Abiding by the findings of the tool, people can expect a reinforced insight into the science of food, which will, in turn, make it easier for them to decide what to eat to lead a healthy lifestyle.                According to the food Compass, anything with a score below 30 should be consumed to the minimum, followed by things falling in the range of 31-69, which should be consumed in moderation.   For example, snack and sweet deserts have acquired an average score of 16.4, which means that these edibles should be consumed with a pinch of salt (not literally). Vegetables and fruits have earned a score ranging between 73.9-100, which suggests that these should occupy a major part of your diet. Poultry scored 42.67, beef scored 24.9, while seafood scored 67 on the food Compass.",
    category: "food",
    date: " /November 17, 2021",
    tags: ["food", "Health"],
    readdate: "3 mins read",
    views: 50,
    claps:52,
  },

  {
    id: 16,
    author: "Rahul Shrestha",
    imgURL:
      "https://images.news18.com/ibnlive/uploads/2021/11/untitled-design-15-16371468153x2.png?impolicy=website&width=510&height=356",
    title: "Dummy Blog 5",
    desc: "People in today’s day and age have become very prudent about what they consume. However, with the influx of multiple brands, new foods, and establishments offering various types of edibles, it is crucial to have a system that rates the vivid variety of foods. Researchers at the Friedman School of Nutrition Science and Policy at Tufts University, Boston, Massachusetts, have devised a nutrient profiling system that tallies and weighs the nutritional characteristics, and rates different kinds of foods depending on their effect on the overall health of the body. Monikered as ‘food Compass,’ this tool has been developed after the research and development done across a period of three years and includes data collected on 8,032 foods and beverages consumed by the American populace, reported Tufts Now - the news website of Tufts University.        “Once you get beyond the general health advice related to food, the public is still oblivious to the method of ranking their meals and the choice of establishments offering food. Therefore, not just consumers, but policymakers and people associated with the food industry aim for guiding people towards healthier food habits,” Dariush Mozaffarian, Dean, Friedman School, was quoted as saying.                The food Compass developed by the researchers’ analyses various foods and beverages around 54 different characteristics across nine domains. Abiding by the findings of the tool, people can expect a reinforced insight into the science of food, which will, in turn, make it easier for them to decide what to eat to lead a healthy lifestyle.                According to the food Compass, anything with a score below 30 should be consumed to the minimum, followed by things falling in the range of 31-69, which should be consumed in moderation.   For example, snack and sweet deserts have acquired an average score of 16.4, which means that these edibles should be consumed with a pinch of salt (not literally). Vegetables and fruits have earned a score ranging between 73.9-100, which suggests that these should occupy a major part of your diet. Poultry scored 42.67, beef scored 24.9, while seafood scored 67 on the food Compass.",
    category: "food",
    date: " /November 17, 2021",
    tags: ["food", "Health"],
    readdate: "3 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 17,
    author: "Rahul Shrestha",
    imgURL:
      "https://images.news18.com/ibnlive/uploads/2021/11/untitled-design-15-16371468153x2.png?impolicy=website&width=510&height=356",
    title: "Dummy Blog 6",
    desc: "People in today’s day and age have become very prudent about what they consume. However, with the influx of multiple brands, new foods, and establishments offering various types of edibles, it is crucial to have a system that rates the vivid variety of foods. Researchers at the Friedman School of Nutrition Science and Policy at Tufts University, Boston, Massachusetts, have devised a nutrient profiling system that tallies and weighs the nutritional characteristics, and rates different kinds of foods depending on their effect on the overall health of the body. Monikered as ‘food Compass,’ this tool has been developed after the research and development done across a period of three years and includes data collected on 8,032 foods and beverages consumed by the American populace, reported Tufts Now - the news website of Tufts University.        “Once you get beyond the general health advice related to food, the public is still oblivious to the method of ranking their meals and the choice of establishments offering food. Therefore, not just consumers, but policymakers and people associated with the food industry aim for guiding people towards healthier food habits,” Dariush Mozaffarian, Dean, Friedman School, was quoted as saying.                The food Compass developed by the researchers’ analyses various foods and beverages around 54 different characteristics across nine domains. Abiding by the findings of the tool, people can expect a reinforced insight into the science of food, which will, in turn, make it easier for them to decide what to eat to lead a healthy lifestyle.                According to the food Compass, anything with a score below 30 should be consumed to the minimum, followed by things falling in the range of 31-69, which should be consumed in moderation.   For example, snack and sweet deserts have acquired an average score of 16.4, which means that these edibles should be consumed with a pinch of salt (not literally). Vegetables and fruits have earned a score ranging between 73.9-100, which suggests that these should occupy a major part of your diet. Poultry scored 42.67, beef scored 24.9, while seafood scored 67 on the food Compass.",
    category: "food",
    date: " /November 17, 2021",
    tags: ["food", "Health"],
    readdate: "3 mins read",
    views: 50,
    claps:52,
  },

  {
    id: 18,
    author: "NDTV",
    imgURL:
      "https://simpleflying.com/wp-content/uploads/2021/11/American-Airlines-Boeing-777-323ER-N732AN-1-1-1000x800.jpg",
    title: "Dummy blog 2",
    desc: "New Delhi: American Airlines relaunched flights to India this week, nearly a decade after stopping them, looking to capitalise on growing demand for non-stop travel amid the coronavirus pandemic, a senior executive of the airline told Reuters.        With travel demand bouncing back at home, American Airlines wants to expand its international network and India was 'one of the biggest untapped markets' for it, said Tom Lattig, managing director of EMEA sales. 'A lot of customers really want to fly non- stop, particularly as we've come through the pandemic. We know there is huge demand for travel between India and the United States so there is an opportunity right now in the middle of the pandemic to come back,' Lattig said in an interview in New Delhi.       American Airlines, which suspended services to India in 2012, started flying between New Delhi and New York on the weekend and will add flights between India's tech city of Bengaluru and Seattle in March.If it succeeds with those two routes, it will add services to India's financial capital of Mumbai, Lattig said.",
    category: "travel",
    date: " /November 14, 2021",
    tags: ["travel", "AirLines"],
    readdate: "6 mins read",
    views: 100,

    claps:52,
  },
  {
    id: 19,
    author: "NDTV",
    imgURL:
      "https://simpleflying.com/wp-content/uploads/2021/11/American-Airlines-Boeing-777-323ER-N732AN-1-1-1000x800.jpg",
    title: "Dummy blog 3",
    desc: "New Delhi: American Airlines relaunched flights to India this week, nearly a decade after stopping them, looking to capitalise on growing demand for non-stop travel amid the coronavirus pandemic, a senior executive of the airline told Reuters.        With travel demand bouncing back at home, American Airlines wants to expand its international network and India was 'one of the biggest untapped markets' for it, said Tom Lattig, managing director of EMEA sales. 'A lot of customers really want to fly non- stop, particularly as we've come through the pandemic. We know there is huge demand for travel between India and the United States so there is an opportunity right now in the middle of the pandemic to come back,' Lattig said in an interview in New Delhi.       American Airlines, which suspended services to India in 2012, started flying between New Delhi and New York on the weekend and will add flights between India's tech city of Bengaluru and Seattle in March.If it succeeds with those two routes, it will add services to India's financial capital of Mumbai, Lattig said.",
    category: "travel",
    date: " /November 14, 2021",
    tags: ["travel", "AirLines"],
    readdate: "6 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 20,
    author: "NDTV",
    imgURL:
      "https://simpleflying.com/wp-content/uploads/2021/11/American-Airlines-Boeing-777-323ER-N732AN-1-1-1000x800.jpg",
    title: "Dummy blog 4",
    desc: "New Delhi: American Airlines relaunched flights to India this week, nearly a decade after stopping them, looking to capitalise on growing demand for non-stop travel amid the coronavirus pandemic, a senior executive of the airline told Reuters.        With travel demand bouncing back at home, American Airlines wants to expand its international network and India was 'one of the biggest untapped markets' for it, said Tom Lattig, managing director of EMEA sales. 'A lot of customers really want to fly non- stop, particularly as we've come through the pandemic. We know there is huge demand for travel between India and the United States so there is an opportunity right now in the middle of the pandemic to come back,' Lattig said in an interview in New Delhi.       American Airlines, which suspended services to India in 2012, started flying between New Delhi and New York on the weekend and will add flights between India's tech city of Bengaluru and Seattle in March.If it succeeds with those two routes, it will add services to India's financial capital of Mumbai, Lattig said.",
    category: "travel",
    date: " /November 14, 2021",
    tags: ["travel", "AirLines"],
    readdate: "6 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 21,
    author: "NDTV",
    imgURL:
      "https://simpleflying.com/wp-content/uploads/2021/11/American-Airlines-Boeing-777-323ER-N732AN-1-1-1000x800.jpg",
    title: "Dummy blog 5",
    desc: "New Delhi: American Airlines relaunched flights to India this week, nearly a decade after stopping them, looking to capitalise on growing demand for non-stop travel amid the coronavirus pandemic, a senior executive of the airline told Reuters.        With travel demand bouncing back at home, American Airlines wants to expand its international network and India was 'one of the biggest untapped markets' for it, said Tom Lattig, managing director of EMEA sales. 'A lot of customers really want to fly non- stop, particularly as we've come through the pandemic. We know there is huge demand for travel between India and the United States so there is an opportunity right now in the middle of the pandemic to come back,' Lattig said in an interview in New Delhi.       American Airlines, which suspended services to India in 2012, started flying between New Delhi and New York on the weekend and will add flights between India's tech city of Bengaluru and Seattle in March.If it succeeds with those two routes, it will add services to India's financial capital of Mumbai, Lattig said.",
    category: "travel",
    date: " /November 14, 2021",
    tags: ["travel", "AirLines"],
    readdate: "6 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 22,
    author: "Rahul Shrestha",
    imgURL: "https://images.indianexpress.com/2021/11/Sonos_Roam_Speaker.jpeg",
    title: "Dummy blog 6",
    desc: "Alphabet Inc.’s Google said it’s the rightful owner of patents on ways to keep music playlists in the cloud that form a key component of a lawsuit Sonos Inc. filed over the Google Play Music system. Sonos called that contention “nonsense.”        Sonos, an early proponent of connected home speakers, has claimed that Google gained knowledge of the technology through a partnership to integrate Google Play into the Sonos platform, and then decided to sell its own product line and undercut Sonos on price.              In a court filing Tuesday, the Alphabet unit said “Google, not Sonos, conceived of the cloud queue idea” and thus should be listed as owner and inventor of two of the Sonos patents. It also contends a 2013 Content Integration Agreement prohibits Sonos from claiming ownership of any technology developed during the partnership.",
    category: "technology",
    date: " /November 14, 2021",
    tags: ["technology", "Google"],
    readdate: "2 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 23,
    author: "Rahul Shrestha",
    imgURL: "https://images.indianexpress.com/2021/11/Sonos_Roam_Speaker.jpeg",
    title: "Dummy blog 7",
    desc: "Alphabet Inc.’s Google said it’s the rightful owner of patents on ways to keep music playlists in the cloud that form a key component of a lawsuit Sonos Inc. filed over the Google Play Music system. Sonos called that contention “nonsense.”        Sonos, an early proponent of connected home speakers, has claimed that Google gained knowledge of the technology through a partnership to integrate Google Play into the Sonos platform, and then decided to sell its own product line and undercut Sonos on price.              In a court filing Tuesday, the Alphabet unit said “Google, not Sonos, conceived of the cloud queue idea” and thus should be listed as owner and inventor of two of the Sonos patents. It also contends a 2013 Content Integration Agreement prohibits Sonos from claiming ownership of any technology developed during the partnership.",
    category: "technology",
    date: " /November 14, 2021",
    tags: ["technology", "Google"],
    readdate: "2 mins read",
    views: 100,

    claps:52,
  },
  {
    id: 24,
    author: "Rahul Shrestha",
    imgURL: "https://images.indianexpress.com/2021/11/Sonos_Roam_Speaker.jpeg",
    title: "Dummy blog 8",
    desc: "Alphabet Inc.’s Google said it’s the rightful owner of patents on ways to keep music playlists in the cloud that form a key component of a lawsuit Sonos Inc. filed over the Google Play Music system. Sonos called that contention “nonsense.”        Sonos, an early proponent of connected home speakers, has claimed that Google gained knowledge of the technology through a partnership to integrate Google Play into the Sonos platform, and then decided to sell its own product line and undercut Sonos on price.              In a court filing Tuesday, the Alphabet unit said “Google, not Sonos, conceived of the cloud queue idea” and thus should be listed as owner and inventor of two of the Sonos patents. It also contends a 2013 Content Integration Agreement prohibits Sonos from claiming ownership of any technology developed during the partnership.",
    category: "technology",
    date: " /November 14, 2021",
    tags: ["technology", "Google"],
    readdate: "2 mins read",
    views: 100,

    claps:52,
  },
  {
    id: 25,
    author: "Rahul Shrestha",
    imgURL:
      "https://www.muscleandfitness.com/wp-content/uploads/2017/09/skull-crushers.jpg?w=940&h=529&crop=1&quality=86&strip=all",
    title: "THE FULL-BODY HOLIDAY WORKOUT PROGRAM",
    desc: "Even the most hardcore lifters can fall victim to the time-sucking demands of the holiday season—parties, family functions, and travel—but that doesn’t mean your physique has to suffer. Instead of cranking out six hard workouts per week, allow yourself some seasonal leeway by cutting it to four. By implementing a program with a strong focus on compound movements you’ll make up for the lost days, and that’s what this month’s program is about: gaining muscle when time allows without missing out on the things that really matter. HOW IT WORKS You’ll train four days per week, but your two toughest, longest workouts will be on the days you can fit them in. Your hardest training should come when you’re rested, ready, and have the most free time around your busy holiday schedule. The quicker, lighter routines will easily fit into a busy day. You can do cardio on your more free days, or simply take time off if time is tight. To customize the program even further, we’ve included alternate exercises to choose from depending on how you feel. Get ready to make gains at the speed of Santa’s sleigh.",
    category: "fitness",
    date: " /November 14, 2021",
    tags: ["fitness", "Google"],
    readdate: "2 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 26,
    author: "Rahul Shrestha",
    imgURL:
      "https://www.muscleandfitness.com/wp-content/uploads/2021/11/Vegan-Loaded-Potato-Cauliflower-Au-Gratin.jpg?w=940&h=529&crop=1&quality=86&strip=all",
    title:
      "MAKE YOUR THANKSGIVING PERFECTLY ‘JERSEYSTYLE’ WITH THIS VEGAN DISH",
    desc: "Michael Newman is the chef with muscles who shot to national fame on Fox’s “MasterChef: Legends.” The Asbury Park, NJ, resident is also the co-founder of the JerseyStyle lifestyle brand, along with his wife and partner Basia, and is an out-and-proud vegan.As we prepare for Thanksgiving, the popular social media personality and “Relationship Sexpert” explains how to celebrate the big day “JerseyStyle.” Newman also shares an exclusive vegan recipe for making the perfect “Vegan Loaded Potato Cauliflower Au Gratin.” (Try saying that after a few Thanksgiving tipples!)",
    category: "fitness",
    date: " /November 14, 2021",
    tags: ["fitness", "Google", "fitness_food"],
    readdate: "2 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 27,
    author: "Rahul Shrestha",
    imgURL:
      "https://www.muscleandfitness.com/wp-content/uploads/2017/09/skull-crushers.jpg?w=940&h=529&crop=1&quality=86&strip=all",
    title: "Dummy blog 8",
    desc: "Michael Newman is the chef with muscles who shot to national fame on Fox’s “MasterChef: Legends.” The Asbury Park, NJ, resident is also the co-founder of the JerseyStyle lifestyle brand, along with his wife and partner Basia, and is an out-and-proud vegan.As we prepare for Thanksgiving, the popular social media personality and “Relationship Sexpert” explains how to celebrate the big day “JerseyStyle.” Newman also shares an exclusive vegan recipe for making the perfect “Vegan Loaded Potato Cauliflower Au Gratin.” (Try saying that after a few Thanksgiving tipples!)",
    category: "fitness",
    date: " /November 14, 2021",
    tags: ["fitness", "Google", "fitness_food"],
    readdate: "2 mins read",
    views: 50,
    claps:52,
  },
  {
    id: 28,
    author: "Rahul Shrestha",
    imgURL:
      "https://www.muscleandfitness.com/wp-content/uploads/2021/11/Vegan-Loaded-Potato-Cauliflower-Au-Gratin.jpg?w=940&h=529&crop=1&quality=86&strip=all",
    title: "Dummy blog 9",
    desc: "Michael Newman is the chef with muscles who shot to national fame on Fox’s “MasterChef: Legends.” The Asbury Park, NJ, resident is also the co-founder of the JerseyStyle lifestyle brand, along with his wife and partner Basia, and is an out-and-proud vegan.As we prepare for Thanksgiving, the popular social media personality and “Relationship Sexpert” explains how to celebrate the big day “JerseyStyle.” Newman also shares an exclusive vegan recipe for making the perfect “Vegan Loaded Potato Cauliflower Au Gratin.” (Try saying that after a few Thanksgiving tipples!)",
    category: "fitness",
    date: " /November 14, 2021",
    tags: ["fitness", "Google", "fitness_food"],
    readdate: "2 mins read",
    views: 50,
    claps:52,
  },
];

export const PostDataContext = createContext(PostData);
